NumPy Retail Analytics Assignment

Business Scenario

You are working as a Data Analyst for SmartMart Retail Stores. The company operates five stores in different cities and sells six major product categories.

Management wants to analyze sales performance, expenses, profits, targets, discounts, inventory, and store-level performance using NumPy.

You are provided with two main NumPy arrays:

sales_data — monthly sales revenue generated by each store for different product categories.

cost_data — total cost incurred by each store for the same product categories.

Part 1: Dataset Creation

In [ ]:
import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)

Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


Part 2: Basic Array Understanding

Question 1: Array Dimensions

The finance manager wants to confirm how many stores and product categories are present in the data.

Write NumPy code to display:

Number of dimensions in sales_data

Shape of sales_data

Total number of values

Data type of the array

Memory occupied by the array

In [ ]:
#Number of dimensions in sales_data
print("Number of dimensions in sales_data:",sales_data.ndim)
#Shape of sales_data
print("Shape of sales_data:",sales_data.shape)
#Total number of values
print("Total number of values:",sales_data.size)
#Data type of the array
print("Data type of the array:",sales_data.dtype)
#Memory occupied by the array
print("Memory occupied by the array:" ,sales_data.nbytes)


Number of dimensions in sales_data: 2
Shape of sales_data: (5, 6)
Total number of values: 30
Data type of the array: int64
Memory occupied by the array: 240


Question 2: Store and Category Count

Calculate the following:

Total number of stores

Total number of product categories

Total number of store-category combinations

In [ ]:
#Total number of stores
print("Total number of stores:",len(stores))
#Total number of product categories
print("Total number of product categories:",len(categories))
#Total number of store-category combinations
print("Total number of store-category combinations:",len(stores)*len(categories))


Total number of stores: 5
Total number of product categories: 6
Total number of store-category combinations: 30


Question 3: Sales Data Type Conversion

The reporting application requires sales values in floating-point format.

Convert sales_data into:

float32

float64

Compare the memory used by both arrays.

In [ ]:
#Convert sales_data into:

#float32
sales_data_folat32 = sales_data.astype("float32")
print("Memory occupied by the array:",sales_data_folat32.nbytes)
#float64
sales_data_folat64 = sales_data.astype("float64")
print("Memory occupied by the array:",sales_data_folat64.nbytes)

Memory occupied by the array: 120
Memory occupied by the array: 240


Part 3: Indexing and Data Extraction

Question 4: Bengaluru Store Analysis

The Bengaluru regional manager wants to review sales for all product categories.

Extract and display the complete sales row for Bengaluru.

In [ ]:
#Extract and display the complete sales row for Bengaluru.
Bengaluru_sales = sales_data[0]
print("Bengaluru sales:",Bengaluru_sales)


Bengaluru sales: [850000 420000 310000 275000 190000 225000]


Question 5: Mumbai Cost Analysis

Extract the total cost incurred by the Mumbai store for all product categories.

In [ ]:
#Mumbai Cost Analysis
Mumbai_total_cost = np.sum(cost_data[3])
print("Mumbai total cost:",Mumbai_total_cost)

Mumbai total cost: 2065000


Question 6: Electronics Sales Across Stores

The electronics department wants to compare its sales performance across all five stores.

Extract the Electronics sales column from sales_data.

In [ ]:
#Extract the Electronics sales column from sales_data.
Electronics_sales = sales_data[:,0]
print("Electronics sales:",Electronics_sales)


Electronics sales: [ 850000  780000  920000 1050000  690000]


Question 7: Clothing Cost Across Stores

Extract the Clothing cost for every store from cost_data.

In [ ]:
#Extract the Clothing cost for every store from cost_data.
Clothing_cost = cost_data[:,2]
print("Clothing cost:",Clothing_cost)

Clothing cost: [220000 210000 245000 265000 205000]


Question 8: Hyderabad Furniture Performance

Find the following for Hyderabad:

Furniture sales

Furniture cost

Furniture profit

In [ ]:
#Furniture sales
Furniture_sales = sales_data[1,3]
print("Furniture sales:",Furniture_sales)
# Furniture cost
Furniture_cost = cost_data[1,3]
print("Furniture cost:",Furniture_cost)
# Furniture profit
Furniture_profit = Furniture_sales - Furniture_cost
print("Furniture profit:",Furniture_profit)


Furniture sales: 310000
Furniture cost: 225000
Furniture profit: 85000


Question 9: Chennai Category Range

Extract Chennai’s sales for the following categories:

Groceries

Clothing

Furniture

Use array slicing.

In [ ]:
#Extract Chennai’s sales for the following categories:
Chennai_sales = sales_data[2,[[-5,-4,-3]]]
print("Chennai sales:",Chennai_sales)

Chennai sales: [[390000 340000 260000]]


Question 10: Selected Store Analysis

Extract sales data for:

Bengaluru

Chennai

Pune

Include only:

Electronics

Clothing

 Use advanced indexing.

In [ ]:
#Extract sales data for:
#Bengaluru
# Chennai
# Pune
# Include only:

# Electronics
# Clothing
# Beauty
Sales_data_preferred_cities = sales_data[[0,2,4],:][:,[0,2,4]]
print("Sales data for preferred cities:",Sales_data_preferred_cities)


Sales data for preferred cities: [[850000 310000 190000]
 [920000 340000 185000]
 [690000 280000 175000]]


Part 4: Sales Aggregation

Question 11: Company-Wide Sales

Calculate the total sales revenue generated by all stores and all categories.

In [ ]:
#Calculate the total sales revenue generated by all stores and all categories.

Total_sales = np.sum(sales_data)
print("Total sales:",Total_sales)

Total sales: 11675000


Question 12: Store-Wise Sales

Calculate total sales revenue for each store.

Display the result together with the store names.

Expected output format:

Bengaluru: total sales

Hyderabad: total sales

Chennai: total sales

Mumbai: total sales

Pune: total sales

In [ ]:
for i in range (len(stores)):
    print(stores[i],":",np.sum(sales_data[i]))

Bengaluru : 2270000
Hyderabad : 2295000
Chennai : 2310000
Mumbai : 2820000
Pune : 1980000


Question 13: Category-Wise Sales

Calculate total sales for each product category across all stores.

Display each category name with its total sales.



In [ ]:
for i in range(len(categories)):
    print(categories[i],":",np.sum(sales_data[:,i]))

Electronics : 4290000
Groceries : 2185000
Clothing : 1600000
Furniture : 1415000
Beauty : 1010000
Sports : 1175000


Question 14: Average Sales Per Store

Calculate the average sales generated by each store across all six product categories.

In [ ]:
#Calculate the average sales generated by each store across all six product categories.

for i in range(len(stores)):
    print("Average sales of stores",stores[i],":",np.mean(sales_data[i]))

Average sales of stores Bengaluru : 378333.3333333333
Average sales of stores Hyderabad : 382500.0
Average sales of stores Chennai : 385000.0
Average sales of stores Mumbai : 470000.0
Average sales of stores Pune : 330000.0


Question 15: Average Sales Per Category

Calculate the average sales of each product category across the five stores.



In [ ]:
#Calculate the average sales of each product category across the five stores.
for i in range (len(categories)):
    print("Average sales of categories",categories[i],":",np.mean(sales_data[:,i]))


Average sales of categories Electronics : 858000.0
Average sales of categories Groceries : 437000.0
Average sales of categories Clothing : 320000.0
Average sales of categories Furniture : 283000.0
Average sales of categories Beauty : 202000.0
Average sales of categories Sports : 235000.0


Question 16: Highest-Selling Store

Identify:

Index of the store with the highest total sales

Name of the store

Total sales generated by that store

Use np.argmax().

In [ ]:
#Index of the store with the highest total sales

Highest_selling_store_index = np.argmax(np.sum(sales_data,axis=1))
print("Index of the store with the highest total sales:",Highest_selling_store_index)
#Name of the store
print("Name of the store:",stores[Highest_selling_store_index])
#Total sales generated by that store
print("Total sales generated by that store:",np.sum(sales_data[Highest_selling_store_index]))


Index of the store with the highest total sales: 3
Name of the store: Mumbai
Total sales generated by that store: 2820000


Question 17: Lowest-Selling Store

Identify the store with the lowest overall sales.

Use np.argmin().

In [ ]:
#Identify the store with the lowest overall sales.
Lowest_selling_store_index = np.argmin(np.sum(sales_data,axis=1))
print("Index of the store with the lowest total sales:",Lowest_selling_store_index)

Index of the store with the lowest total sales: 4


Question 18: Highest-Selling Category

Find the product category that generated the highest total sales across the company.

In [ ]:
#Find the product category that generated the highest total sales across the company.
categorywise_total_sales = np.sum(sales_data,axis=0)
Highest_selling_category_index = np.argmax(categorywise_total_sales)
print("Name of the category:",categories[Highest_selling_category_index])



Name of the category: Electronics


Question 19: Lowest-Selling Category

Find the product category with the lowest total sales across all stores.

In [ ]:
#Find the product category with the lowest total sales across all stores.
categorywise_total_sales = np.sum(sales_data,axis=0)
Lowest_selling_category_index = np.argmin(categorywise_total_sales)
print("Name of the category:",categories[Lowest_selling_category_index])

Name of the category: Beauty


Part 5: Cost Analysis

Question 20: Total Company Cost

Calculate the total cost incurred by SmartMart across all stores and product categories.

In [ ]:
#Calculate the total cost incurred by SmartMart across all stores and product categories.
Total_cost = np.sum(cost_data)
print("Total cost of SmartMart:",Total_cost)

Total cost of SmartMart: 8600000


Question 21: Store-Wise Cost

Calculate the total cost incurred by each store.

In [ ]:
#Calculate the total cost incurred by each store.
for i in range(len(stores)):
    print("Total cost of stores",stores[i],":",np.sum(cost_data[i]))


Total cost of stores Bengaluru : 1665000
Total cost of stores Hyderabad : 1685000
Total cost of stores Chennai : 1710000
Total cost of stores Mumbai : 2065000
Total cost of stores Pune : 1475000


Question 22: Category-Wise Cost

Calculate the total cost incurred for each product category across all stores.

In [ ]:
#Calculate the total cost incurred for each product category across all stores.
for i in range(len(categories)):
    print("Total cost of categories",categories[i],":",np.sum(cost_data[:,i]))

Total cost of categories Electronics : 3250000
Total cost of categories Groceries : 1660000
Total cost of categories Clothing : 1145000
Total cost of categories Furniture : 1045000
Total cost of categories Beauty : 665000
Total cost of categories Sports : 835000


Question 23: Most Expensive Store

Identify the store with the highest total operating cost.

In [ ]:
#Identify the store with the highest total operating cost.
Most_expensive_store_index = np.argmax(np.sum(cost_data,axis=1))
print("Name of the store:",stores[Most_expensive_store_index])


Name of the store: Mumbai


Question 24: Lowest-Cost Store

Identify the store with the lowest total cost.

In [ ]:
#Identify the store with the lowest total cost.
Lowest_cost_store_index = np.argmin(np.sum(cost_data,axis=1))
print("Name of the store:",stores[Lowest_cost_store_index])

Name of the store: Pune


Question 25: Most Expensive Product Category

Determine which product category has the highest total cost across all stores.

In [ ]:
#Determine which product category has the highest total cost across all stores.

categorywise_total_cost = np.sum(cost_data,axis=0)
Most_expensive_category_index = np.argmax(categorywise_total_cost)
print("Name of the category:",categories[Most_expensive_category_index])

Name of the category: Electronics


Part 6: Profit Analysis Using Two Arrays

Question 26: Profit Matrix

Calculate the profit generated for every store and product category.

Use:
profit_data = sales_data - cost_data

Display the complete profit matrix.

In [ ]:
#Calculate the profit generated for every store and product category.
profit_data = sales_data - cost_data
print("Profit matrix:\n",profit_data)


Profit matrix:
 [[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]


Question 27: Store-Wise Profit

Calculate the total profit generated by each store.

In [ ]:
#Calculate the total profit generated by each store.
profit_data = sales_data - cost_data
for i in range(len(stores)):
    print("Total profit of stores",stores[i],":",np.sum(profit_data[i]))



Total profit of stores Bengaluru : 605000
Total profit of stores Hyderabad : 610000
Total profit of stores Chennai : 600000
Total profit of stores Mumbai : 755000
Total profit of stores Pune : 505000


Question 28: Category-Wise Profit

Calculate the total profit generated by each product category.


In [ ]:
#Calculate the total profit generated by each product category.
profit_data = sales_data - cost_data
for i in range(len(categories)):
    print("Total profit of categories",categories[i],":",np.sum(profit_data[:,i]))

Total profit of categories Electronics : 1040000
Total profit of categories Groceries : 525000
Total profit of categories Clothing : 455000
Total profit of categories Furniture : 370000
Total profit of categories Beauty : 345000
Total profit of categories Sports : 340000


Question 29: Most Profitable Store

Identify the store that generated the highest total profit.

Display:
Store name

Total sales

Total cost

Total profit

In [ ]:
#Total sales
storewise_total_sales = np.sum(sales_data,axis=1)

#Total cost
storewise_total_cost = np.sum(cost_data,axis=1)

#Total profit
storewise_total_profit = storewise_total_sales - storewise_total_cost

print("store name :",stores[Highest_selling_store_index])
print("Total sales:",storewise_total_sales[Highest_selling_store_index])
print("Total cost:",storewise_total_cost[Highest_selling_store_index])
print("Total profit:",storewise_total_profit[Highest_selling_store_index])


store name : Mumbai
Total sales: 2820000
Total cost: 2065000
Total profit: 755000


Question 30: Least Profitable Store

Identify the store that generated the lowest total profit.

In [ ]:
#Identify the store that generated the lowest total profit.
storewise_total_profit = np.sum(profit_data,axis=1)
lowest_index = np.argmin(storewise_total_profit)
print("store name :",stores[lowest_index])


store name : Pune


Question 31: Most Profitable Category

Find the category with the highest total profit across all stores.

In [ ]:
#Find the category with the highest total profit across all stores.
categorywise_total_profit = np.sum(profit_data,axis=0)
Most_profitable_category_index = np.argmax(categorywise_total_profit)
print("Name of the category:",categories[Most_profitable_category_index])


Name of the category: Electronics


Question 32: Least Profitable Category

Find the category with the lowest total profit.

In [ ]:
#Find the category with the lowest total profit.
categorywise_total_profit = np.sum(profit_data,axis=0)
Least_profitable_category_index = np.argmin(categorywise_total_profit)
print("Name of the category:",categories[Least_profitable_category_index])

Name of the category: Sports


Question 33: Maximum Individual Profit

Find the highest profit generated by any single store-category combination.

Display:

Profit amount

Store name

Product category

Use np.unravel_index().

In [ ]:
#Profit amount
maximum_profit = np.max(profit_data)
print("Maximum profit:",maximum_profit)
#Store name
Max_index = np.unravel_index(np.argmax(profit_data),profit_data.shape)[0]
print("Store name:",stores[Max_index])
#Product category
Max_index = np.unravel_index(np.argmax(profit_data),profit_data.shape)[1]
print("Product category:",categories[Max_index])


Maximum profit: 260000
Store name: Mumbai
Product category: Electronics


Question 34: Minimum Individual Profit

Find the smallest profit generated by a store-category combination.

Display the corresponding store and category.



In [ ]:
minimum_profit = np.min(profit_data)
print("Minimum profit:",minimum_profit)
min_index = np.unravel_index(np.argmin(profit_data),profit_data.shape)[0]
print("Store name:",stores[min_index])
min_index = np.unravel_index(np.argmin(profit_data),profit_data.shape)[1]
print("Product category:",categories[min_index])

Minimum profit: 55000
Store name: Pune
Product category: Furniture


Part 7: Profit Margin Analysis

Question 35: Profit Margin Matrix

Calculate the profit margin percentage for every store-category combination.

Use:
profit_margin = (profit_data / sales_data) * 100

Round the result to two decimal places.

In [ ]:
import numpy as np
sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

profit_data = sales_data - cost_data
profit_margin = (profit_data / sales_data) * 100
profit_margin = np.round(profit_margin,2)
print("profit margin after round,2:",profit_margin)



profit margin after round,2: [[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]


Question 36: Store-Wise Profit Margin

Calculate the overall profit margin percentage for each store using:

Store Profit Margin =Total Store Profit / Total Store Sales × 100

In [ ]:
#Calculate the overall profit margin percentage for each store using:
overall_profit_margin = (np.sum(profit_data,axis=1)/np.sum(sales_data,axis=1))*100
print("overall profit margin:",overall_profit_margin)


overall profit margin: [26.65198238 26.5795207  25.97402597 26.77304965 25.50505051]


Question 37: Category-Wise Profit Margin

Calculate the overall profit margin percentage for each product category.

In [ ]:
#Calculate the overall profit margin percentage for each product category.
overall_profit_margin_category = (np.sum(profit_data,axis=0)/np.sum(sales_data,axis=0))*100
print("overall profit margin category:",overall_profit_margin_category)

overall profit margin category: [24.24242424 24.02745995 28.4375     26.14840989 34.15841584 28.93617021]


Question 38: Best Store by Profit Margin

Identify the store with the highest overall profit margin.

In [ ]:
#Identify the store with the highest overall profit margin.
profit_margin = np.array([
    [24.71, 25.00, 29.03, 25.45, 34.21, 28.89],
    [24.36, 23.91, 28.81, 27.42, 33.33, 29.17],
    [23.91, 24.36, 27.94, 25.00, 35.14, 27.91],
    [24.76, 23.53, 29.33, 27.54, 34.00, 29.31],
    [23.19, 23.46, 26.79, 24.44, 34.29, 29.27]
])

stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

highest_store_index = np.argmax(overall_profit_margin)
print("Name of the store:",stores[highest_store_index])

Name of the store: Mumbai


Question 39: Best Category by Profit Margin

Identify the product category with the highest profit margin.

In [ ]:
#Identify the product category with the highest profit margin.
profit_margin = np.array([
    [24.71, 25.00, 29.03, 25.45, 34.21, 28.89],
    [24.36, 23.91, 28.81, 27.42, 33.33, 29.17],
    [23.91, 24.36, 27.94, 25.00, 35.14, 27.91],
    [24.76, 23.53, 29.33, 27.54, 34.00, 29.31],
    [23.19, 23.46, 26.79, 24.44, 34.29, 29.27]
])
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

highest_category_index = np.argmax(overall_profit_margin_category)
print("Name of the category:",categories[highest_category_index])


Name of the category: Beauty


Question 40: Low-Margin Transactions

Management considers a profit margin below 22% to be weak.

Find all store-category combinations where the profit margin is below 22%.

Display:

Store , Category ,Sales , Profit , Profit margin Use Boolean indexing.


In [ ]:
low_margin_mask = profit_margin < 22
rows, cols = np.where(low_margin_mask)
for i, j in zip(rows, cols):
    print(f"Store: {stores[i]}, Category: {categories[j]}, "
          f"Sales: {sales_data[i, j]}, Profit: {profit_data[i, j]}, "
          f"Profit Margin: {profit_margin[i, j]}%")
print("Minimum Profit Margin:", profit_margin.min())



Minimum Profit Margin: 23.19


Part 8: Boolean Filtering

Question 41: High Sales Values

Find all sales values greater than ₹5,00,000.

In [ ]:
#Find all sales values greater than ₹5,00,000.

sales_values = sales_data[sales_data > 500000]
print("Sales values greater than ₹5,00,000:", sales_values)

Sales values greater than ₹5,00,000: [ 850000  780000  920000 1050000  510000  690000]


Question 42: Low Sales Values

Find all sales values below ₹2,00,000.

In [ ]:
sales_values = sales_data[sales_data < 200000]
print("Sales values below 200000:", sales_values)

Sales values below 200000: [190000 185000 175000]


Question 43: High Profit Values

Find all store-category combinations where profit is greater than ₹1,50,000.

In [ ]:
profit_data = sales_data - cost_data
high_profit_mask = profit_data > 150000
rows, cols = np.where(high_profit_mask)
for i, j in zip(rows, cols):
    print(f"Store: {stores[i]}, Category: {categories[j]}, "
          f"Profit: {profit_data[i, j]}")

Store: Bengaluru, Category: Electronics, Profit: 210000
Store: Hyderabad, Category: Electronics, Profit: 190000
Store: Chennai, Category: Electronics, Profit: 220000
Store: Mumbai, Category: Electronics, Profit: 260000
Store: Pune, Category: Electronics, Profit: 160000


Question 44: Moderate Sales Range

Find sales values between ₹2,50,000 and ₹5,00,000.

Use np.logical_and().

In [ ]:
#Find sales values between ₹2,50,000 and ₹5,00,000.
sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

sales_values = sales_data[np.logical_and(sales_data >= 250000, sales_data <= 500000)]
print("Sales values between ₹2,50,000 and ₹5,00,000:", sales_values)


Sales values between ₹2,50,000 and ₹5,00,000: [420000 310000 275000 460000 295000 310000 390000 340000 260000 375000
 345000 250000 290000 405000 280000]


Question 45: Premium Performance

A store-category combination is considered premium when:

Sales are greater than ₹5,00,000

Profit is greater than ₹1,50,000

Find all premium-performing combinations.

In [ ]:
premium_mask = np.logical_and(sales_data > 500000, profit_data > 150000)
rows, cols = np.where(premium_mask)
for i, j in zip(rows, cols):
    print(f"Store: {stores[i]}, Category: {categories[j]}, "
          f"Sales: {sales_data[i, j]}, Profit: {profit_data[i, j]}")

Store: Bengaluru, Category: Electronics, Sales: 850000, Profit: 210000
Store: Hyderabad, Category: Electronics, Sales: 780000, Profit: 190000
Store: Chennai, Category: Electronics, Sales: 920000, Profit: 220000
Store: Mumbai, Category: Electronics, Sales: 1050000, Profit: 260000
Store: Pune, Category: Electronics, Sales: 690000, Profit: 160000


Question 46: Underperforming Combinations

A store-category combination is considered underperforming when:

Sales are below ₹2,50,000

Profit margin is below 25%

Find all such combinations.

In [ ]:
underperforming_mask = np.logical_and(sales_data < 250000, profit_margin < 25)
rows, cols = np.where(underperforming_mask)
for i, j in zip(rows, cols):
    print(f"Store: {stores[i]}, Category: {categories[j]}, "
          f"Sales: {sales_data[i, j]}, Profit Margin: {profit_margin[i, j]}%")

Store: Pune, Category: Furniture, Sales: 225000, Profit Margin: 24.44%


Question 47: Category Performance Classification

Create a new array that classifies every sales value as:

"High" when sales are at least ₹5,00,000

"Medium" when sales are between ₹2,50,000 and ₹4,99,999

"Low" when sales are below ₹2,50,000

Use np.where() or np.select().

In [ ]:
classification = np.where(sales_data >= 500000, "High",
                         np.where(np.logical_and(sales_data >= 250000, sales_data <= 499999), "Medium", "Low"))
print("Classification of sales values:\n", classification)


Classification of sales values:
 [['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'High' 'Medium' 'Medium' 'Medium' 'Medium']
 ['High' 'Medium' 'Medium' 'Low' 'Low' 'Low']]


Part 9: Target-Based Analysis

In [ ]:
sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])

Question 48: Target Comparison

Compare every store’s category sales against sales_targets.

Use NumPy broadcasting.

In [ ]:
sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]])

comparsion = sales_data >= sales_targets
print("comparsion:",comparsion)

comparsion: [[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


Question 49: Target Achievement Matrix

Create a Boolean array where:

True means the store achieved the category target

False means the store failed to achieve the target

In [ ]:
#True means the store achieved the category target
#False means the store failed to achieve the target
sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])
sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

target_achieved_mask = sales_data >= sales_targets
print("Target achieved mask:\n", target_achieved_mask)

Target achieved mask:
 [[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


Question 50: Target Achievement Count

Calculate the number of categories in which each store achieved its target.

In [ ]:
#Calculate the number of categories in which each store achieved its target.
target_achieved_count = np.sum(target_achieved_mask, axis=1)
print("Number of categories in which each store achieved its target:", target_achieved_count)

Number of categories in which each store achieved its target: [1 4 2 6 0]


Question 51: Best Target-Performing Store

Find the store that achieved the highest number of category targets.

In [ ]:
#Find the store that achieved the highest number of category targets.
highest_store_index = np.argmax(target_achieved_count)
print("Best performing store:", stores[highest_store_index])

Best performing store: Mumbai


Question 52: Target Achievement by Category

Calculate how many stores achieved the target for each product category.

In [ ]:
#Calculate how many stores achieved the target for each product category.
target_achieved_count = np.sum(target_achieved_mask, axis=0)
print("Number of stores achieved target for each category:", target_achieved_count)

Number of stores achieved target for each category: [3 2 2 2 2 2]


Question 53: Sales Target Variance

Calculate the difference between actual sales and target sales for every store.

Use:Variance = Actual Sales - Target Sales

In [ ]:
#Calculate the difference between actual sales and target sales for every store.

Variance = sales_data - sales_targets
print("Variance:",Variance)

Variance: [[  50000  -30000  -10000  -25000  -10000   -5000]
 [ -20000   10000  -25000   10000   10000   10000]
 [ 120000  -60000   20000  -40000  -15000  -15000]
 [ 250000   60000   55000   45000   50000   60000]
 [-110000  -45000  -40000  -75000  -25000  -25000]]


Question 54: Percentage Above or Below Target

Calculate the percentage variance from the target using:

Percentage Variance =(Actual Sales - Target Sales) / Target Sales × 100

In [ ]:
#Calculate the percentage variance from the target using:

percentage_variance = (sales_data - sales_targets) / sales_targets * 100
print("Percentage Variance:",percentage_variance)

Percentage Variance: [[  6.25        -6.66666667  -3.125       -8.33333333  -5.
   -2.17391304]
 [ -2.5          2.22222222  -7.8125       3.33333333   5.
    4.34782609]
 [ 15.         -13.33333333   6.25       -13.33333333  -7.5
   -6.52173913]
 [ 31.25        13.33333333  17.1875      15.          25.
   26.08695652]
 [-13.75       -10.         -12.5        -25.         -12.5
  -10.86956522]]


Question 55: Stores Missing Electronics Target

Identify stores that failed to achieve the Electronics sales target.

In [ ]:
#Identify stores that failed to achieve the Electronics sales target.
Electronics_Target =800000
electronics_target_index = 0
missing_electronics_target_mask = sales_data[:, electronics_target_index] < sales_targets[electronics_target_index]
missing_electronics_target_stores = stores[missing_electronics_target_mask]
print("Stores missing Electronics target:", missing_electronics_target_stores)


Stores missing Electronics target: ['Hyderabad' 'Pune']


Question 56: Stores Achieving All Targets

Check whether any store achieved its target in all six product categories.

Use np.all().

In [ ]:
#Check whether any store achieved its target in all six product categories.
all_target_achieved_mask = np.all(target_achieved_mask, axis=1)
any_store_achieved_all_targets = np.any(all_target_achieved_mask)
if any_store_achieved_all_targets:
    print("Any store achieved all targets in all categories.")
else:
    print("No store achieved all targets in all categories.")

print("Store-wise all-target achievement mask:", all_target_achieved_mask)
print("Stores that achieved all targets:", stores[all_target_achieved_mask])


Any store achieved all targets in all categories.
Store-wise all-target achievement mask: [False False False  True False]
Stores that achieved all targets: ['Mumbai']


Question 57: Stores Achieving At Least One Target

Identify stores that achieved at least one category target.

Use np.any().



In [ ]:
#Identify stores that achieved at least one category target.
at_least_one_target_achieved_mask = np.any(target_achieved_mask, axis=1)
stores_at_least_one_target_achieved = stores[at_least_one_target_achieved_mask]
print("Stores achieving at least one target:", stores_at_least_one_target_achieved)



Stores achieving at least one target: ['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai']


Part 10: Discount Scenario

#SmartMart plans to offer category-wise discounts:

discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
])

Question 58: Discount Amount Matrix

Calculate the discount amount for each store-category combination.

Use broadcasting.

In [ ]:
#Calculate the discount amount for each store-category combination.
discount_rates= np.array([0.10,0.05,0.15,0.12,0.08,0.10])
discount_amount = sales_data * discount_rates
print("Discount amount:",discount_amount)

Discount amount: [[ 85000.  21000.  46500.  33000.  15200.  22500.]
 [ 78000.  23000.  44250.  37200.  16800.  24000.]
 [ 92000.  19500.  51000.  31200.  14800.  21500.]
 [105000.  25500.  56250.  41400.  20000.  29000.]
 [ 69000.  20250.  42000.  27000.  14000.  20500.]]


Question 59: Sales After Discount

Calculate the net sales value after applying the category-wise discounts.

In [ ]:
#Calculate the net sales value after applying the category-wise discounts.
net_sales = sales_data - discount_amount
print("Net sales after discount:",net_sales)

Net sales after discount: [[765000. 399000. 263500. 242000. 174800. 202500.]
 [702000. 437000. 250750. 272800. 193200. 216000.]
 [828000. 370500. 289000. 228800. 170200. 193500.]
 [945000. 484500. 318750. 303600. 230000. 261000.]
 [621000. 384750. 238000. 198000. 161000. 184500.]]


Question 60: Profit After Discount

Assuming costs remain unchanged, calculate the new profit after the discounts are applied.

In [ ]:
#Assuming costs remain unchanged, calculate the new profit after the discounts are applied.
New_profit_after_discount = net_sales - cost_data
print("New Profit after discount:",profit_after_discount)


New Profit after discount: [[125000.  84000.  43500.  37000.  49800.  42500.]
 [112000.  87000.  40750.  47800.  53200.  46000.]
 [128000.  75500.  44000.  33800.  50200.  38500.]
 [155000.  94500.  53750.  53600.  65000.  56000.]
 [ 91000.  74750.  33000.  28000.  46000.  39500.]]


Question 61: Profit Margin After Discount

Calculate the new profit margin after applying discounts.

In [ ]:
#Calculate the new profit margin after applying discounts.
New_profit_margin_after_discount = (New_profit_after_discount / net_sales) * 100
print("New profit margin after discount:",New_profit_margin_after_discount)


New profit margin after discount: [[16.33986928 21.05263158 16.5085389  15.2892562  28.48970252 20.98765432]
 [15.95441595 19.90846682 16.25124626 17.52199413 27.53623188 21.2962963 ]
 [15.4589372  20.37786775 15.22491349 14.77272727 29.4947121  19.89664083]
 [16.4021164  19.50464396 16.8627451  17.65480896 28.26086957 21.4559387 ]
 [14.65378422 19.42820013 13.86554622 14.14141414 28.57142857 21.40921409]]


Question 62: Loss-Making Transactions

Check whether any store-category combination becomes loss-making after discounts.

Display the affected store and category names.

In [ ]:
#Check whether any store-category combination becomes loss-making after discounts.

loss_making_mask = New_profit_after_discount < 0
rows, cols = np.where(loss_making_mask)
for i, j in zip(rows, cols):
    print(f"Store: {stores[i]}, Category: {categories[j]}, "
          f"Profit After Discount: {New_profit_after_discount[i, j]}")
if len(rows) == 0:
    print("no loss making stores-category")





no loss making stores-category


Question 63: Discount Impact

Calculate how much total revenue the company loses because of the proposed discounts.

In [ ]:
#Calculate how much total revenue the company loses because of the proposed discounts.
total_loss = np.sum(New_profit_after_discount[loss_making_mask])
print("Total loss due to discounts:", total_loss)

Total loss due to discounts: 0.0


Question 64: Store Most Affected by Discounts

Identify the store that loses the highest amount of revenue due to discounts.

In [ ]:
#Identify the store that loses the highest amount of revenue due to discounts.
# Find indices of loss-making entries
rows, cols = np.where(loss_making_mask)

if len(rows) > 0:

    worst_index = np.argmin(New_profit_after_discount[loss_making_mask])
    store_index = rows[worst_index]
    category_index = cols[worst_index]

    print("Store most affected by discounts:", stores[store_index])
    print("Category most affected:", categories[category_index])
    print("Profit After Discount:", New_profit_after_discount[store_index, category_index])
else:
    print("No Loss Making")


No Loss Making


Part 11: Tax and Price Adjustment

#The government introduces category-wise tax rates:

tax_rates = np.array([
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
])


Question 65: Tax Collection Matrix

Calculate the tax collected on sales for each store and category.

In [ ]:
#Calculate the tax collected on sales for each store and category.
tax_rates = np.array([
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
])

tax_collected = sales_data * tax_rates
print("Tax collected:",tax_collected)

Tax collected: [[153000.  21000.  37200.  49500.  34200.  27000.]
 [140400.  23000.  35400.  55800.  37800.  28800.]
 [165600.  19500.  40800.  46800.  33300.  25800.]
 [189000.  25500.  45000.  62100.  45000.  34800.]
 [124200.  20250.  33600.  40500.  31500.  24600.]]


Question 66: Sales Including Tax

Calculate the final customer billing value after adding tax.

In [ ]:
#Calculate the final customer billing value after adding tax.
sales_after_tax = sales_data + tax_collected
print("Sales after tax:",sales_after_tax)

Sales after tax: [[1003000.  441000.  347200.  324500.  224200.  252000.]
 [ 920400.  483000.  330400.  365800.  247800.  268800.]
 [1085600.  409500.  380800.  306800.  218300.  240800.]
 [1239000.  535500.  420000.  407100.  295000.  324800.]
 [ 814200.  425250.  313600.  265500.  206500.  229600.]]


Question 67: Store-Wise Tax Collection

Calculate the total tax collected by each store.

In [ ]:
#Calculate the total tax collected by each store.
total_tax_collected = np.sum(tax_collected, axis=1)
print("Total tax collected by each store:", total_tax_collected)

Total tax collected by each store: [321900. 321200. 331800. 401400. 274650.]


Question 68: Category-Wise Tax Collection

Calculate total tax collected for each category.

In [ ]:
#Calculate total tax collected for each category.
total_tax_collected = np.sum(tax_collected, axis=0)
print("Total tax collected for each category:", total_tax_collected)

Total tax collected for each category: [772200. 109250. 192000. 254700. 181800. 141000.]


Question 69: Highest Tax-Contributing Store

Identify the store that contributes the highest tax amount.

In [ ]:
#Identify the store that contributes the highest tax amount
total_tax_collected = np.sum(tax_collected, axis=1)
highest_tax_store_index = np.argmax(total_tax_collected)
print("Highest tax-contributing store:", stores[highest_tax_store_index])

Highest tax-contributing store: Mumbai


Part 12: Array Modification

Question 70: Updated Pune Electronics Sales

The Pune store reports that its Electronics sales were entered incorrectly.

Update Pune Electronics sales from ₹6,90,000 to ₹7,40,000.

Make the change in a copied array without modifying the original array.

In [ ]:
#Update Pune Electronics sales from ₹6,90,000 to ₹7,40,000.
#Make the change in a copied array without modifying the original array.
sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

updated_sales_data = sales_data.copy()
updated_sales_data[4, 0] = 740000
print("Updated sales data:\n", updated_sales_data)
print("Original sales data (unchanged):\n", sales_data)


Updated sales data:
 [[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 740000  405000  280000  225000  175000  205000]]
Original sales data (unchanged):
 [[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]


Question 71: Revised Beauty Cost

Due to supplier negotiations, Beauty product costs are reduced by 8% for all stores.

Create an updated cost array.

In [ ]:
#Due to supplier negotiations, Beauty product costs are reduced by 8% for all stores.
#Create an updated cost array.

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

updated_cost_data = cost_data.copy()
updated_cost_data[:, 4] = cost_data[:, 4] * 0.92
print("Updated cost data:\n", updated_cost_data)
print("Original cost data :\n", cost_data)

Updated cost data:
 [[640000 315000 220000 205000 115000 160000]
 [590000 350000 210000 225000 128800 170000]
 [700000 295000 245000 195000 110400 155000]
 [790000 390000 265000 250000 151800 205000]
 [530000 310000 205000 170000 105800 145000]]
Original cost data :
 [[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


Question 72: Furniture Cost Increase

Furniture costs increase by 12% for all stores.

Update only the Furniture column.

In [ ]:
#Furniture costs increase by 12% for all stores.
#Update only the Furniture column.
updated_cost_data = cost_data.copy()
updated_cost_data[:, 3] = cost_data[:, 3] * 1.12
print("Updated cost data:\n", updated_cost_data)

Updated cost data:
 [[640000 315000 220000 229600 125000 160000]
 [590000 350000 210000 252000 140000 170000]
 [700000 295000 245000 218400 120000 155000]
 [790000 390000 265000 280000 165000 205000]
 [530000 310000 205000 190400 115000 145000]]


Question 73: Store Closure Simulation

Assume the Pune store is temporarily closed.

Remove Pune’s sales and cost data from the analysis using np.delete().

In [ ]:
#Remove Pune’s sales and cost data from the analysis using np.delete().
updated_sales_data = np.delete(sales_data, 4, axis=0)
updated_cost_data = np.delete(cost_data, 4, axis=0)
print("Updated sales data:\n", updated_sales_data)
print("Updated cost data:\n", updated_cost_data)

Updated sales data:
 [[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]]
Updated cost data:
 [[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]]


Question 74: Adding a New Store

A new Delhi store is opened with the following data:

delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])

delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])


Add Delhi to both arrays using np.vstack().

Also add "Delhi" to the stores array.

In [ ]:
#Add Delhi to both arrays using np.vstack().
#Also add "Delhi" to the stores array.

delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])
delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])

updated_sales_data = np.vstack((sales_data, delhi_sales))
updated_cost_data = np.vstack((cost_data, delhi_cost))
stores = np.append(stores, "Delhi")
print("Updated sales data:\n", updated_sales_data)
print("Updated cost data:\n", updated_cost_data)
print("Updated stores array:", stores)

stores = np.array(['Bengaluru', 'Hyderabad', 'Chennai', 'Mumbai', 'Pune', 'Delhi', 'Delhi', 'Delhi'])
stores_no_delhi = np.unique(stores[stores != "Delhi"])
stores = np.append(stores_no_delhi, "Delhi")

print("Updated stores array:", stores)


Updated sales data:
 [[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 880000  475000  330000  290000  215000  250000]]
Updated cost data:
 [[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]
 [665000 360000 235000 215000 145000 180000]]
Updated stores array: ['Bengaluru' 'Chennai' 'Delhi' 'Hyderabad' 'Mumbai' 'Pune' 'Delhi']
Updated stores array: ['Bengaluru' 'Chennai' 'Hyderabad' 'Mumbai' 'Pune' 'Delhi']


Part 13: Sorting and Ranking

Question 76: Sort Stores by Sales

Sort stores in ascending order based on total sales.

Display store names and sales totals.

In [ ]:
#Sort stores in ascending order based on total sales.
totals_sales = np.sum(updated_sales_data, axis=1)
sorted_indices = np.argsort(totals_sales)
sorted_stores = stores[sorted_indices]
sorted_sales = totals_sales[sorted_indices]
print("Sorted stores by sales:")
for store, sales in zip(sorted_stores, sorted_sales):
    print(f"{store}: {sales}")




Sorted stores by sales:
Pune: 1980000
Bengaluru: 2270000
Chennai: 2295000
Hyderabad: 2310000
Delhi: 2440000
Mumbai: 2820000


Question 77: Rank Stores by Profit

Rank stores from highest to lowest total profit.

Use np.argsort().

In [ ]:
#Rank stores from highest to lowest total profit.

profit = updated_sales_data - updated_cost_data
total_profit = np.sum(profit, axis=1)
ranked_indices = np.argsort(total_profit)[::-1]
ranked_stores = stores[ranked_indices]
ranked_profit = total_profit[ranked_indices]
print("Ranked stores by profit:")
for store, profit in zip(ranked_stores, ranked_profit):
    print(f"{store}: {profit}")

Ranked stores by profit:
Mumbai: 755000
Delhi: 640000
Chennai: 610000
Bengaluru: 605000
Hyderabad: 600000
Pune: 505000


Question 78: Sort Categories by Revenue

Sort product categories from highest to lowest total revenue.

In [ ]:
#Sort product categories from highest to lowest total revenue.
total_revenue = np.sum(updated_sales_data, axis=0)
sorted_indices = np.argsort(total_revenue)[::-1]
sorted_categories = categories[sorted_indices]
sorted_revenue = total_revenue[sorted_indices]
print("Sorted categories by revenue:")
for category, revenue in zip(sorted_categories, sorted_revenue):
    print(f"{category}: {revenue}")

Sorted categories by revenue:
Electronics: 5170000
Groceries: 2660000
Clothing: 1930000
Furniture: 1705000
Sports: 1425000
Beauty: 1225000


Question 79: Top Three Store-Category Sales

Find the three highest individual sales values in the complete sales matrix.

Display their:  Sales value , Store name,Category name


In [ ]:
#Find the three highest individual sales values in the complete sales matrix.
flat_indices = np.argsort(sales_data.flatten())[-3:]
flat_indices = np.unravel_index(flat_indices, sales_data.shape)
flat_sales = sales_data[flat_indices]
flat_stores = stores[flat_indices[0]]
flat_categories = categories[flat_indices[1]]
print("Top three store-category sales:")
for sales, store, category in zip(flat_sales, flat_stores, flat_categories):
    print(f"Sales: {sales}, Store: {store}, Category: {category}")


Top three store-category sales:
Sales: 850000, Store: Bengaluru, Category: Electronics
Sales: 920000, Store: Hyderabad, Category: Electronics
Sales: 1050000, Store: Mumbai, Category: Electronics


Question 80: Bottom Three Profits

Find the three lowest profit values in the profit matrix.

In [ ]:
#Find the three lowest profit values in the profit matrix.
import numpy as np

# Profit matrix (example: New_profit_after_discount)
New_profit_after_discount = np.array([
    [125000,  84000,  43500,  37000,  49800,  42500],
    [112000,  87000,  40750,  47800,  53200,  46000],
    [128000,  75500,  44000,  33800,  50200,  38500],
    [155000,  94500,  53750,  53600,  65000,  56000],
    [ 91000,  74750,  33000,  28000,  46000,  39500]
])
flat_indices = np.argsort(New_profit_after_discount.flatten())[:3]
rows, cols = np.unravel_index(flat_indices, New_profit_after_discount.shape)
lowest_profits = New_profit_after_discount[rows, cols]
lowest_stores = stores[rows]
lowest_categories = categories[cols]
print("Lowest three profits:")
for profit, store, category in zip(lowest_profits, lowest_stores, lowest_categories):
    print(f"Profit: {profit}, Store: {store}, Category: {category}")



Lowest three profits:
Profit: 28000, Store: Pune, Category: Furniture
Profit: 33000, Store: Pune, Category: Clothing
Profit: 33800, Store: Hyderabad, Category: Furniture


Part 14: Statistical Analysis

Question 81: Sales Statistics
Calculate the following for the complete sales array:

Minimum ,Maximum,Mean,Median,Standard deviation, Variance,25th percentile, 50th percentile, 75th percentile


In [ ]:
sales_data = np.array(
    [[850000, 420000, 310000, 275000, 190000, 225000],
     [780000, 460000, 295000, 310000, 210000, 240000],
     [920000, 390000, 340000, 260000, 185000, 215000],
     [1050000, 510000, 375000, 345000, 250000, 290000],
     [690000, 405000, 280000, 225000, 175000, 205000]]
)

min_sales = np.min(sales_data)
max_sales = np.max(sales_data)
mean_sales = np.mean(sales_data)
median_sales = np.median(sales_data)
std_sales = np.std(sales_data)
var_sales = np.var(sales_data)
percentile_25 = np.percentile(sales_data, 25)
percentile_50 = np.percentile(sales_data, 50)
percentile_75 = np.percentile(sales_data, 75)

print("Minimum Sales:", min_sales)
print("Maximum Sales:", max_sales)
print("Mean Sales:", mean_sales)
print("Median Sales:", median_sales)
print("Standard Deviation of Sales:", std_sales)
print("Variance of Sales:", var_sales)
print("25th Percentile (Q1) of Sales:", percentile_25)
print("50th Percentile (Median) of Sales:", percentile_50)
print("75th Percentile (Q3) of Sales:", percentile_75)

Minimum Sales: 175000
Maximum Sales: 1050000
Mean Sales: 389166.6666666667
Median Sales: 302500.0
Standard Deviation of Sales: 230322.53954448793
Variance of Sales: 53048472222.222206
25th Percentile (Q1) of Sales: 228750.0
50th Percentile (Median) of Sales: 302500.0
75th Percentile (Q3) of Sales: 416250.0


Question 82: Store-Wise Standard Deviation

Calculate the sales standard deviation for every store.

Use this value to determine which store has the most variation between product categories.

In [ ]:
#Calculate the sales standard deviation for every store.
store_std = np.std(sales_data, axis=1)
print("Standard deviation for each store:")
for store, std in zip(stores, store_std):
    print(f"{store}: {std}")

max_var_index = np.argmax(store_std)
max_var_store = stores[max_var_index]
print(f"Store with the highest variation: {max_var_store}")





Standard deviation for each store:
Bengaluru: 223059.53365762145
Chennai: 194502.57067709928
Hyderabad: 249265.58794453225
Mumbai: 271860.871280391
Pune: 177200.4514666935
Store with the highest variation: Mumbai


Question 83: Category-Wise Standard Deviation

Determine which product category has the highest variation in sales across stores.

In [ ]:
#Determine which product category has the highest variation in sales across stores.
category_std = np.std(sales_data, axis=0)
print("Standard deviation for each category:")
for category, std in zip(categories, category_std):
    print(f"{category}: {std}")

max_var_index = np.argmax(category_std)
max_var_category = categories[max_var_index]
print(f"Category with the highest variation: {max_var_category}")


Standard deviation for each category:
Electronics: 122539.78945632312
Groceries: 43312.815655415434
Clothing: 33911.64991562634
Furniture: 41303.75285612677
Beauty: 26570.660511172846
Sports: 29832.867780352597
Category with the highest variation: Electronics


Question 84: Sales Above Company Average

Calculate the company-wide average sales value.

Count how many store-category sales values are above this average.

In [ ]:
#Calculate the company-wide average sales value.
company_avg_sales = np.mean(sales_data)
print("Company-wide average sales:", company_avg_sales)
above_avg_count = np.sum(sales_data > company_avg_sales)
print("Number of store-category sales above average:", above_avg_count)

Company-wide average sales: 389166.6666666667
Number of store-category sales above average: 10


Question 85: Outlier Detection

Treat any sales value greater than:

Mean + 1.5 × Standard Deviation as a high-value outlier.

Identify all such sales values.

In [ ]:
#Mean + 1.5 × Standard Deviation as a high-value outlier.

mean_sales = np.mean(sales_data)
std_sales = np.std(sales_data)
outlier_threshold = mean_sales + 1.5 * std_sales

outlier_indices = np.where(sales_data > outlier_threshold)
outlier_values = sales_data[outlier_indices]
outlier_stores = stores[outlier_indices[0]]
outlier_categories = categories[outlier_indices[1]]
print("High-value outliers:")
for value, store, category in zip(outlier_values, outlier_stores, outlier_categories):
    print(f"Value: {value}, Store: {store}, Category: {category}")



High-value outliers:
Value: 850000, Store: Bengaluru, Category: Electronics
Value: 780000, Store: Chennai, Category: Electronics
Value: 920000, Store: Hyderabad, Category: Electronics
Value: 1050000, Store: Mumbai, Category: Electronics


Part 15: Reshaping and Transformation

Question 86: Flatten Sales Data

Convert the two-dimensional sales array into a one-dimensional array using:

flatten() , ravel()

Explain the difference between the two methods.

In [ ]:
#Convert the two-dimensional sales array into a one-dimensional array using:
flat_sales_copy = sales_data.flatten()
print("Flattened sales data using flatten():", flat_sales_copy[:10])
flat_sales_view = sales_data.ravel()
print("Flattened sales data using ravel():", flat_sales_view[:10])

Flattened sales data using flatten(): [850000 420000 310000 275000 190000 225000 780000 460000 295000 310000]
Flattened sales data using ravel(): [850000 420000 310000 275000 190000 225000 780000 460000 295000 310000]


Question 87: Reshape Sales Data

Reshape the 5 × 6 sales array into:

3 × 10

10 × 3

2 × 15

15 × 2

Verify that no data is lost.

In [ ]:
#Reshape the 5 × 6 sales array into:
reshaped_sales_3x10 = sales_data.reshape(3, 10)
print("Reshaped sales data (3x10):\n", reshaped_sales_3x10)
reshaped_sales_10x3 = sales_data.reshape(10, 3)
print("Reshaped sales data (10x3):\n", reshaped_sales_10x3)
reshaped_sales_2x15 = sales_data.reshape(2, 15)
print("Reshaped sales data (2x15):\n", reshaped_sales_2x15)
reshaped_sales_15x2 = sales_data.reshape(15, 2)
print("Reshaped sales data (15x2):\n", reshaped_sales_15x2)


Reshaped sales data (3x10):
 [[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000]
 [ 210000  240000  920000  390000  340000  260000  185000  215000 1050000
   510000]
 [ 375000  345000  250000  290000  690000  405000  280000  225000  175000
   205000]]
Reshaped sales data (10x3):
 [[ 850000  420000  310000]
 [ 275000  190000  225000]
 [ 780000  460000  295000]
 [ 310000  210000  240000]
 [ 920000  390000  340000]
 [ 260000  185000  215000]
 [1050000  510000  375000]
 [ 345000  250000  290000]
 [ 690000  405000  280000]
 [ 225000  175000  205000]]
Reshaped sales data (2x15):
 [[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000  210000  240000  920000  390000  340000]
 [ 260000  185000  215000 1050000  510000  375000  345000  250000  290000
   690000  405000  280000  225000  175000  205000]]
Reshaped sales data (15x2):
 [[ 850000  420000]
 [ 310000  275000]
 [ 190000  225000]
 [ 780000  460000]
 [ 295000  310000]
 [ 210000  

Question 88: Transpose Sales Data

Transpose the sales array so that:

Rows represent product categories

Columns represent stores

Display the new shape.

In [ ]:
#Transpose the sales array so that:
transposed_sales = sales_data.T
print("Transposed sales data:\n", transposed_sales)
print("New shape of transposed sales data:", transposed_sales.shape)


Transposed sales data:
 [[ 850000  780000  920000 1050000  690000]
 [ 420000  460000  390000  510000  405000]
 [ 310000  295000  340000  375000  280000]
 [ 275000  310000  260000  345000  225000]
 [ 190000  210000  185000  250000  175000]
 [ 225000  240000  215000  290000  205000]]
New shape of transposed sales data: (6, 5)


Question 89: Combined Sales and Cost Array

Stack sales_data and cost_data vertically.

Display the resulting shape.

In [ ]:
#Stack sales_data and cost_data vertically.

combined_data = np.vstack((sales_data, cost_data))
print("Combined sales and cost data:\n", combined_data)
print("Shape of combined sales and cost data:", combined_data.shape)


Combined sales and cost data:
 [[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 640000  315000  220000  205000  125000  160000]
 [ 590000  350000  210000  225000  140000  170000]
 [ 700000  295000  245000  195000  120000  155000]
 [ 790000  390000  265000  250000  165000  205000]
 [ 530000  310000  205000  170000  115000  145000]]
Shape of combined sales and cost data: (10, 6)


Question 90: Store-Level Combined Data

Create a three-dimensional array where:

First layer contains sales data

Second layer contains cost data

Use np.stack().

Display the shape of the new array.

In [ ]:
#Create a three-dimensional array where:
combined_data = np.stack((sales_data, cost_data), axis=0)
print("Combined sales and cost data (three-dimensional):\n", combined_data)
print("Shape of combined sales and cost data (three-dimensional):", combined_data.shape)


Combined sales and cost data (three-dimensional):
 [[[ 850000  420000  310000  275000  190000  225000]
  [ 780000  460000  295000  310000  210000  240000]
  [ 920000  390000  340000  260000  185000  215000]
  [1050000  510000  375000  345000  250000  290000]
  [ 690000  405000  280000  225000  175000  205000]]

 [[ 640000  315000  220000  205000  125000  160000]
  [ 590000  350000  210000  225000  140000  170000]
  [ 700000  295000  245000  195000  120000  155000]
  [ 790000  390000  265000  250000  165000  205000]
  [ 530000  310000  205000  170000  115000  145000]]]
Shape of combined sales and cost data (three-dimensional): (2, 5, 6)


Question 91: Missing Value Detection

Find:Total number of missing values

Location of missing values

Stores and categories containing missing values

In [ ]:
#Total number of missing values
missing_mask =np.isnan(sales_data)
total_missing = np.sum(missing_mask)
missing_indices = np.where(missing_mask)
missing_stores = stores[missing_indices[0]]
missing_categories = categories[missing_indices[1]]

print("total missing values:", total_missing)
print("Location of missing values:")
print("Stores:", missing_stores)
print("Categories:", missing_categories)



total missing values: 0
Location of missing values:
Stores: []
Categories: []


Question 92: Replace Missing Values with Zero

Replace all missing sales values with zero.

In [ ]:
#Replace Missing Values with Zero
sales_data_filled = np.nan_to_num(sales_data, nan=0)
print("Sales data with missing values replaced with zero:\n", sales_data_filled)


Sales data with missing values replaced with zero:
 [[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]


Question 93: Replace with Company Average

Replace missing values with the overall average of available sales values.

Use np.nanmean().

In [ ]:
#Replace with Company Average
company_avg_sales = np.nanmean(sales_data)
sales_data_filled = np.where(np.isnan(sales_data), company_avg_sales, sales_data)
print("Sales data with missing values replaced with company average:\n", sales_data_filled)


Sales data with missing values replaced with company average:
 [[ 850000.  420000.  310000.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  310000.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  510000.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  175000.  205000.]]


Question 94: Replace with Category Average

Replace each missing value with the average sales value of its respective product category.

In [ ]:
#Replace each missing value with the average sales value of its respective product category.
category_averages = np.nanmean(sales_data, axis=0)
sales_data_filled = np.where(np.isnan(sales_data), category_averages, sales_data)
print("Sales data with missing values replaced with category averages:\n", sales_data_filled)

Sales data with missing values replaced with category averages:
 [[ 850000.  420000.  310000.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  310000.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  510000.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  175000.  205000.]]


Question 95: Missing Value Impact

Compare total sales before and after replacing missing values with zero.

In [ ]:
#Compare total sales before and after replacing missing values with zero.
total_sales_before = np.sum(sales_data)
total_sales_after = np.sum(sales_data_filled)
print("Total sales before replacing missing values with zero:", total_sales_before)
print("Total sales after replacing missing values with zero:", total_sales_after)

Total sales before replacing missing values with zero: 11675000
Total sales after replacing missing values with zero: 11675000.0


Part 17: Conditional Business Decisions

Question 96: Store Performance Labels

Classify each store based on total sales:

"Excellent": Total sales above ₹28,00,000

"Good": Total sales between ₹24,00,000 and ₹28,00,000

"Needs Improvement": Total sales below ₹24,00,000

Use np.select().

In [ ]:
#Use np.select().
storewise_total_sales = np.sum(sales_data, axis=1)
conditions = [
    storewise_total_sales > 2800000,
    (storewise_total_sales >= 2400000) & (storewise_total_sales <= 2800000),
    storewise_total_sales < 2400000
]
choices = [
    "Excellent",
    "Good",
    "Needs Improvement"
]
store_performance_labels = np.select(conditions, choices, default="Unknown")
print("Store Performance Labels:")
for store, label in zip(stores, store_performance_labels):
    print(f"{store}: {label}")


Store Performance Labels:
Bengaluru: Needs Improvement
Chennai: Needs Improvement
Hyderabad: Needs Improvement
Mumbai: Excellent
Pune: Needs Improvement


Question 97: Profitability Classification

Classify each store-category combination as:

"Highly Profitable": Profit above ₹2,00,000

"Profitable": Profit between ₹1,00,000 and ₹2,00,000

"Low Profit": Profit below ₹1,00,000

"Loss": Profit below zero

In [ ]:
#Classify each store-category combination as:
import numpy as np

New_profit_after_discount = np.array([
    [125000,  84000,  43500,  37000,  49800,  42500],
    [112000,  87000,  40750,  47800,  53200,  46000],
    [128000,  75500,  44000,  33800,  50200,  38500],
    [155000,  94500,  53750,  53600,  65000,  56000],
    [ 91000,  74750,  33000,  28000,  46000,  39500]
])

stores = np.array(['Bengaluru', 'Hyderabad', 'Chennai', 'Mumbai', 'Pune'])
categories = np.array(['Electronics', 'Clothing', 'Furniture', 'Groceries', 'Toys', 'Sports'])

conditions = [
    New_profit_after_discount > 200000,
    (New_profit_after_discount >= 100000) & (New_profit_after_discount <= 200000),
    (New_profit_after_discount < 100000) & (New_profit_after_discount > 0),
    New_profit_after_discount < 0
]

labels = ["Highly Profitable", "Profitable", "Low Profit", "Loss"]

profitability_labels = np.select(conditions, labels, default="Unknown")

print("Profitability Labels:")
for i, store in enumerate(stores):
    for j, category in enumerate(categories):
        print(f"{store}-{category}: Profit={New_profit_after_discount[i,j]}, Label={profitability_labels[i,j]}")


Profitability Labels:
Bengaluru-Electronics: Profit=125000, Label=Profitable
Bengaluru-Clothing: Profit=84000, Label=Low Profit
Bengaluru-Furniture: Profit=43500, Label=Low Profit
Bengaluru-Groceries: Profit=37000, Label=Low Profit
Bengaluru-Toys: Profit=49800, Label=Low Profit
Bengaluru-Sports: Profit=42500, Label=Low Profit
Hyderabad-Electronics: Profit=112000, Label=Profitable
Hyderabad-Clothing: Profit=87000, Label=Low Profit
Hyderabad-Furniture: Profit=40750, Label=Low Profit
Hyderabad-Groceries: Profit=47800, Label=Low Profit
Hyderabad-Toys: Profit=53200, Label=Low Profit
Hyderabad-Sports: Profit=46000, Label=Low Profit
Chennai-Electronics: Profit=128000, Label=Profitable
Chennai-Clothing: Profit=75500, Label=Low Profit
Chennai-Furniture: Profit=44000, Label=Low Profit
Chennai-Groceries: Profit=33800, Label=Low Profit
Chennai-Toys: Profit=50200, Label=Low Profit
Chennai-Sports: Profit=38500, Label=Low Profit
Mumbai-Electronics: Profit=155000, Label=Profitable
Mumbai-Clothing: Pro

Question 98: Expansion Recommendation

A store is eligible for expansion when:

Total sales are above ₹25,00,000

Total profit is above ₹7,00,000

Overall profit margin is above 25%

Identify eligible stores.

In [ ]:
storewise_sales = np.sum(sales_data, axis=1)
storewise_profit = np.sum(sales_data - cost_data, axis=1)


store_profit_margin = (storewise_profit / storewise_sales) * 100

eligible = (storewise_sales > 2500000) & (storewise_profit > 700000) & (store_profit_margin > 25)
eligible_stores = stores[eligible]
print("Expansion Recommendation:")
for store, sales, profit, margin, is_eligible in zip(stores, storewise_sales, storewise_profit, store_profit_margin, eligible):
    status = "Eligible for Expansion" if is_eligible else "Not Eligible"
    print(f"{store}: Sales={sales}, Profit={profit}, Margin={margin:.2f}%, Status={status}")

Expansion Recommendation:
Bengaluru: Sales=2270000, Profit=605000, Margin=26.65%, Status=Not Eligible
Hyderabad: Sales=2295000, Profit=610000, Margin=26.58%, Status=Not Eligible
Chennai: Sales=2310000, Profit=600000, Margin=25.97%, Status=Not Eligible
Mumbai: Sales=2820000, Profit=755000, Margin=26.77%, Status=Eligible for Expansion
Pune: Sales=1980000, Profit=505000, Margin=25.51%, Status=Not Eligible


Question 99: Category Promotion Recommendation

A product category should receive additional promotion when:

Average sales are below ₹3,00,000

Profit margin is above 25%

Identify the categories that satisfy these conditions.

In [ ]:
#A product category should receive additional promotion when:

categories = np.array(['Electronics', 'Clothing', 'Furniture', 'Groceries', 'Toys', 'Sports'])
category_sales = np.sum(sales_data, axis=0)
category_profit = np.sum(sales_data - cost_data, axis=0)

category_avg_sales = np.mean(sales_data, axis=0)

category_margin = (category_profit / category_sales) * 100
eligible = (category_avg_sales < 300000) & (category_margin > 25)


print("Category Promotion Recommendation:")
for cat, avg, margin, is_eligible in zip(categories, category_avg_sales, category_margin, eligible):
    status = "Needs Promotion" if is_eligible else "No Promotion"
    print(f"{cat}: Avg Sales={avg:.0f}, Margin={margin:.2f}%, Status={status}")


Category Promotion Recommendation:
Electronics: Avg Sales=858000, Margin=24.24%, Status=No Promotion
Clothing: Avg Sales=437000, Margin=24.03%, Status=No Promotion
Furniture: Avg Sales=320000, Margin=28.44%, Status=No Promotion
Groceries: Avg Sales=283000, Margin=26.15%, Status=Needs Promotion
Toys: Avg Sales=202000, Margin=34.16%, Status=Needs Promotion
Sports: Avg Sales=235000, Margin=28.94%, Status=Needs Promotion


Question 100: Cost Optimization Recommendation

Find store-category combinations where:

Cost is greater than ₹2,50,000

Profit margin is below 25%

These combinations should be reviewed for cost optimization.

In [ ]:
#Find store-category combinations where
storewise_sales = np.sum(sales_data, axis=1)
storewise_profit = np.sum(sales_data - cost_data, axis=1)

store_profit_margin = (storewise_profit / storewise_sales) * 100
eligible = (storewise_sales > 250000) & (store_profit_margin < 25)
eligible_stores = stores[eligible]
print("Cost Optimization Recommendation:")
for store, sales, profit, margin, is_eligible in zip(stores, storewise_sales, storewise_profit, store_profit_margin, eligible):
    status = "Needs Cost Optimization" if is_eligible else "No Cost Optimization"
    print(f"{store}: Sales={sales}, Profit={profit}, Margin={margin:.2f}%, Status={status}")



Cost Optimization Recommendation:
Bengaluru: Sales=2270000, Profit=605000, Margin=26.65%, Status=No Cost Optimization
Hyderabad: Sales=2295000, Profit=610000, Margin=26.58%, Status=No Cost Optimization
Chennai: Sales=2310000, Profit=600000, Margin=25.97%, Status=No Cost Optimization
Mumbai: Sales=2820000, Profit=755000, Margin=26.77%, Status=No Cost Optimization
Pune: Sales=1980000, Profit=505000, Margin=25.51%, Status=No Cost Optimization


Question 101: Closing Stock

Calculate closing stock using:

Closing Stock = Opening Stock - Units Sold

In [7]:
#Calculate closing stock using:
import numpy as np
opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])
print("Closing Stock:")
closing_stock = opening_stock - units_sold
print(closing_stock)
print("opening Stock:",opening_stock)
print("units sold:",units_sold)


Closing Stock:
[[25 70 60 25 60 40]
 [25 80 50 25 60 45]
 [25 70 50 25 60 40]
 [25 80 55 30 65 45]
 [25 70 55 20 55 40]]
opening Stock: [[120 450 300  90 250 180]
 [110 500 280 100 270 200]
 [130 420 320  85 240 170]
 [150 550 350 120 300 220]
 [100 400 260  75 220 160]]
units sold: [[ 95 380 240  65 190 140]
 [ 85 420 230  75 210 155]
 [105 350 270  60 180 130]
 [125 470 295  90 235 175]
 [ 75 330 205  55 165 120]]


Question 102: Low-Stock Identification

Identify store-category combinations where closing stock is below 30 units.

In [8]:
#Identify store-category combinations where closing stock is below 30 units.
stores = np.array(["Bengaluru", "Hyderabad", "Chennai", "Mumbai", "Pune"])
categories = np.array(["Electronics", "Groceries", "Clothing", "Furniture", "Beauty","Sports"
])
low_stock_indices = np.where(closing_stock < 30)
low_stock_stores = stores[low_stock_indices[0]]
low_stock_categories = categories[low_stock_indices[1]]
print("Low-Stock Identification:")
for store, category in zip(low_stock_stores, low_stock_categories):
    print(f"{store}-{category}: Closing Stock below 30={closing_stock[low_stock_indices]}")


Low-Stock Identification:
Bengaluru-Electronics: Closing Stock below 30=[25 25 25 25 25 25 25 25 20]
Bengaluru-Furniture: Closing Stock below 30=[25 25 25 25 25 25 25 25 20]
Hyderabad-Electronics: Closing Stock below 30=[25 25 25 25 25 25 25 25 20]
Hyderabad-Furniture: Closing Stock below 30=[25 25 25 25 25 25 25 25 20]
Chennai-Electronics: Closing Stock below 30=[25 25 25 25 25 25 25 25 20]
Chennai-Furniture: Closing Stock below 30=[25 25 25 25 25 25 25 25 20]
Mumbai-Electronics: Closing Stock below 30=[25 25 25 25 25 25 25 25 20]
Pune-Electronics: Closing Stock below 30=[25 25 25 25 25 25 25 25 20]
Pune-Furniture: Closing Stock below 30=[25 25 25 25 25 25 25 25 20]


Question 103: Stock Availability Percentage

Calculate the percentage of opening stock that remains unsold.

In [9]:
#Calculate the percentage of opening stock that remains unsold.
opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])
unsold_stock_percentage = (closing_stock / opening_stock) * 100
print("unsold persentage of opening stock unsold:",unsold_stock_percentage)


unsold persentage of opening stock unsold: [[20.83333333 15.55555556 20.         27.77777778 24.         22.22222222]
 [22.72727273 16.         17.85714286 25.         22.22222222 22.5       ]
 [19.23076923 16.66666667 15.625      29.41176471 25.         23.52941176]
 [16.66666667 14.54545455 15.71428571 25.         21.66666667 20.45454545]
 [25.         17.5        21.15384615 26.66666667 25.         25.        ]]


Question 104: Fast-Moving Products

A product is considered fast-moving when more than 80% of its opening stock has been sold.

Identify fast-moving store-category combinations.

In [10]:
#A product is considered fast-moving when more than 80% of its opening stock has been sold.
fast_moving_indices = np.where(unsold_stock_percentage < 20)

fast_moving_stores = stores[fast_moving_indices[0]]
fast_moving_categories = categories[fast_moving_indices[1]]

print("Fast-Moving Products:")
for i, (store, category) in enumerate(zip(fast_moving_stores, fast_moving_categories)):
    unsold_val = unsold_stock_percentage[fast_moving_indices][i]
    print(f"{store}-{category}: Unsold Percentage={unsold_val:.2f}%")





Fast-Moving Products:
Bengaluru-Groceries: Unsold Percentage=15.56%
Hyderabad-Groceries: Unsold Percentage=16.00%
Hyderabad-Clothing: Unsold Percentage=17.86%
Chennai-Electronics: Unsold Percentage=19.23%
Chennai-Groceries: Unsold Percentage=16.67%
Chennai-Clothing: Unsold Percentage=15.62%
Mumbai-Electronics: Unsold Percentage=16.67%
Mumbai-Groceries: Unsold Percentage=14.55%
Mumbai-Clothing: Unsold Percentage=15.71%
Pune-Groceries: Unsold Percentage=17.50%


Question 105: Category-Wise Units Sold

Calculate the total units sold for each product category.

In [11]:
#Calculate the total units sold for each product category.

catogorywise_total_units_sold = np.sum(units_sold, axis=0)
print("Category-Wise Units Sold:")
for category, units in zip(categories, catogorywise_total_units_sold):
    print(f"{category}: Total Units Sold={units}")


Category-Wise Units Sold:
Electronics: Total Units Sold=485
Groceries: Total Units Sold=1950
Clothing: Total Units Sold=1240
Furniture: Total Units Sold=345
Beauty: Total Units Sold=980
Sports: Total Units Sold=720


Question 106: Store-Wise Units Sold

Calculate total units sold by each store.

In [12]:
#Calculate total units sold by each store.
storewise_total_units_sold = np.sum(units_sold, axis=1)
print("Store-Wise Units Sold:")
for store, units in zip(stores, storewise_total_units_sold):
    print(f"{store}: Total Units Sold={units}")

Store-Wise Units Sold:
Bengaluru: Total Units Sold=1110
Hyderabad: Total Units Sold=1175
Chennai: Total Units Sold=1095
Mumbai: Total Units Sold=1390
Pune: Total Units Sold=950


Question 107: Best Store by Unit Sales

Identify the store that sold the highest total number of units.

In [17]:
#Identify the store that sold the highest total number of units.
import numpy as np
storewise_total_units_sold = np.sum(units_sold, axis=1)
highest_sold_store_index = np.argmax(storewise_total_units_sold)
highest_sold_store = stores[highest_sold_store_index]
highest_units = storewise_total_units_sold[highest_sold_store_index]
print(f"storewise highest sales: {highest_sold_store} with Total Units Sold={highest_units}")



storewise highest sales: Mumbai with Total Units Sold=1390


Question 108: Reorder Requirement

A store should reorder a category when closing stock is below 25 units.

Create a Boolean reorder matrix.

In [18]:
#A store should reorder a category when closing stock is below 25 units.

reorder_matrix = closing_stock < 25
print("Reorder Requirement:")
print(reorder_matrix)

Reorder Requirement:
[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False  True False False]]


Question 109: Reorder Quantity

Assume each category must maintain 100 units after reordering.

Calculate reorder quantities only for combinations where closing stock is below 25.

For all other combinations, return zero.

In [20]:
#Assume each category must maintain 100 units after reordering
closing_stock = np.array([
    [25, 70, 60, 25, 60, 40],
    [25, 80, 50, 25, 60, 45],
    [25, 70, 50, 25, 60, 40],
    [25, 80, 55, 30, 65, 45],
    [25, 70, 55, 20, 55, 40]
])
reorder_quantities = np.zeros_like(closing_stock)
reorder_quantities[closing_stock < 25] = 100 - closing_stock[closing_stock < 25]
print("Reorder Quantity:")
print(reorder_quantities)



Reorder Quantity:
[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0 80  0  0]]


Part 19: Advanced NumPy Questions

Question 110: Cumulative Store Sales

Calculate cumulative category sales for each store using np.cumsum().

In [24]:
#Question 110: Cumulative Store Sales
#Calculate cumulative category sales for each store using np.cumsum().
sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])
cumulative_sales = np.cumsum(sales_data, axis=1)
print("Cumulative Store Sales:")
print(cumulative_sales)

Cumulative Store Sales:
[[ 850000 1270000 1580000 1855000 2045000 2270000]
 [ 780000 1240000 1535000 1845000 2055000 2295000]
 [ 920000 1310000 1650000 1910000 2095000 2310000]
 [1050000 1560000 1935000 2280000 2530000 2820000]
 [ 690000 1095000 1375000 1600000 1775000 1980000]]


Question 111: Cumulative Company Sales

Flatten the sales array and calculate cumulative company sales.

In [25]:
#Flatten the sales array and calculate cumulative company sales.

flattened_sales = sales_data.flatten()
cumulative_company_sales = np.cumsum(flattened_sales)
print("Cumulative Company Sales:")
print(cumulative_company_sales)

Cumulative Company Sales:
[  850000  1270000  1580000  1855000  2045000  2270000  3050000  3510000
  3805000  4115000  4325000  4565000  5485000  5875000  6215000  6475000
  6660000  6875000  7925000  8435000  8810000  9155000  9405000  9695000
 10385000 10790000 11070000 11295000 11470000 11675000]


#Question 112: Sales Difference Between Categories

Calculate the difference between consecutive category sales for each store using np.diff().

In [26]:
#Calculate the difference between consecutive category sales for each store using np.diff().

sales_difference = np.diff(sales_data, axis=1)
print("Sales Difference Between Categories:")
print(sales_difference)


Sales Difference Between Categories:
[[-430000 -110000  -35000  -85000   35000]
 [-320000 -165000   15000 -100000   30000]
 [-530000  -50000  -80000  -75000   30000]
 [-540000 -135000  -30000  -95000   40000]
 [-285000 -125000  -55000  -50000   30000]]


#Question 113: Unique Sales Values

Find all unique sales values in sales_data.

Also count the frequency of each value.

In [29]:
#Find all unique sales values in sales_data.
#Also count the frequency of each value.
unique_sales_values, frequency = np.unique(sales_data, return_counts=True)
print("Unique Sales Values:",unique_sales_values)
print("Frequency of Each Value:",frequency)


Unique Sales Values: [ 175000  185000  190000  205000  210000  215000  225000  240000  250000
  260000  275000  280000  290000  295000  310000  340000  345000  375000
  390000  405000  420000  460000  510000  690000  780000  850000  920000
 1050000]
Frequency of Each Value: [1 1 1 1 1 1 2 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1]


Question 114: Search for Specific Sales

Check whether the value ₹4,20,000 exists in the sales array.

Return its location.

In [30]:
#Check whether the value ₹4,20,000 exists in the sales array.
#Return its location.

sales_value = 420000
location = np.where(sales_data == sales_value)
if len(location[0]) > 0:
    print(f"Value {sales_value} exists at location {location}")
else:
    print(f"Value {sales_value} does not exist in the sales array")



Value 420000 exists at location (array([0]), array([1]))


Question 115: Compare Sales and Cost

Create a Boolean array showing whether sales are greater than cost for every combination.

Verify whether all combinations are profitable using np.all().

In [31]:
#Create a Boolean array showing whether sales are greater than cost for every combination.
#Verify whether all combinations are profitable using np.all().
sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])


sales_greater_than_cost = sales_data > cost_data
all_profitable = np.all(sales_greater_than_cost)
print("Sales Greater Than Cost:")
print(sales_greater_than_cost)
print("All Combinations Are Profitable:",all_profitable)


Sales Greater Than Cost:
[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]
All Combinations Are Profitable: True


Question 116: Clip Profit Values

For reporting purposes, management wants profit values limited to:

Minimum: ₹75,000

Maximum: ₹2,50,000

Use np.clip() to create a reporting profit array.

In [36]:
#For reporting purposes, management wants profit values limited to:

profit_data = sales_data - cost_data
reporting_profit = np.clip(profit_data, 75000, 250000)
print("Reporting Profit Values:")
print(reporting_profit)


Reporting Profit Values:
[[210000 105000  90000  75000  75000  75000]
 [190000 110000  85000  85000  75000  75000]
 [220000  95000  95000  75000  75000  75000]
 [250000 120000 110000  95000  85000  85000]
 [160000  95000  75000  75000  75000  75000]]


Question 117: Normalize Sales Data

Normalize all sales values using min-max normalization:

Normalized Sales =(Sales - Minimum Sales) / (Maximum Sales - Minimum Sales)


In [37]:
#Normalize all sales values using min-max normalization:
#Normalized Sales =(Sales - Minimum Sales) / (Maximum Sales - Minimum Sales)

normalized_sales = (sales_data - np.min(sales_data)) / (np.max(sales_data) - np.min(sales_data))
print("Normalized Sales Data:")
print(normalized_sales)


Normalized Sales Data:
[[0.77142857 0.28       0.15428571 0.11428571 0.01714286 0.05714286]
 [0.69142857 0.32571429 0.13714286 0.15428571 0.04       0.07428571]
 [0.85142857 0.24571429 0.18857143 0.09714286 0.01142857 0.04571429]
 [1.         0.38285714 0.22857143 0.19428571 0.08571429 0.13142857]
 [0.58857143 0.26285714 0.12       0.05714286 0.         0.03428571]]


Question 118: Standardize Sales Data

Standardize sales using:

Standardized Sales =(Sales - Mean Sales) / Standard Deviation

In [38]:
#Standardize sales using:
#Standardized Sales =(Sales - Mean Sales) / Standard Deviation

standardized_sales = (sales_data - np.mean(sales_data)) / np.std(sales_data)
print("Standardized Sales Data:")
print(standardized_sales)

Standardized Sales Data:
[[ 2.00081735  0.13387024 -0.34372088 -0.49568169 -0.86472938 -0.71276857]
 [ 1.69689573  0.30753974 -0.40884695 -0.34372088 -0.77789463 -0.64764251]
 [ 2.30473897  0.00361811 -0.21346876 -0.56080776 -0.88643807 -0.75618594]
 [ 2.86916484  0.52462661 -0.06150795 -0.19176007 -0.60422513 -0.43055563]
 [ 1.30613936  0.06874418 -0.47397301 -0.71276857 -0.92985544 -0.79960332]]


Question 119: Round Values

Convert profit margin values into:

Two decimal places

Nearest whole number

Floor values

Ceiling values

In [39]:
#Convert profit margin values into:


profit_margin = (sales_data - cost_data) / sales_data
print("Profit Margin Values:")
print(profit_margin)

rounded_profit_margin = np.round(profit_margin, 2)
print("Rounded Profit Margin Values:")
print(rounded_profit_margin)

nearest_whole_profit_margin = np.round(profit_margin)
print("Nearest Whole Number Profit Margin Values:")
print(nearest_whole_profit_margin)

floor_profit_margin = np.floor(profit_margin)
print("Floor Values of Profit Margin Values:")
print(floor_profit_margin)

ceiling_profit_margin = np.ceil(profit_margin)
print("Ceiling Values of Profit Margin Values:")
print(ceiling_profit_margin)



Profit Margin Values:
[[0.24705882 0.25       0.29032258 0.25454545 0.34210526 0.28888889]
 [0.24358974 0.23913043 0.28813559 0.27419355 0.33333333 0.29166667]
 [0.23913043 0.24358974 0.27941176 0.25       0.35135135 0.27906977]
 [0.24761905 0.23529412 0.29333333 0.27536232 0.34       0.29310345]
 [0.23188406 0.2345679  0.26785714 0.24444444 0.34285714 0.29268293]]
Rounded Profit Margin Values:
[[0.25 0.25 0.29 0.25 0.34 0.29]
 [0.24 0.24 0.29 0.27 0.33 0.29]
 [0.24 0.24 0.28 0.25 0.35 0.28]
 [0.25 0.24 0.29 0.28 0.34 0.29]
 [0.23 0.23 0.27 0.24 0.34 0.29]]
Nearest Whole Number Profit Margin Values:
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Floor Values of Profit Margin Values:
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Ceiling Values of Profit Margin Values:
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.

Question 120: Save and Load Data

Save the following arrays as NumPy binary files:

sales_data.npy

cost_data.npy

profit_data.npy

Load them back and verify that the loaded arrays are equal to the original arrays.

In [ ]:
'''Part 20: Final Retail Analytics Project
Prepare a complete NumPy-based retail performance report.

Your report must contain the following information:

Company Summary
Total company sales
Total company cost
Total company profit
Overall company profit margin
Average transaction value
Highest individual sales value
Lowest individual sales value
Store Summary
For every store, display:

Total sales
Total cost
Total profit
Profit margin
Number of category targets achieved
Total units sold
Expansion eligibility
Category Summary
For every category, display:

Total sales
Total cost
Total profit
Profit margin
Average sales
Number of stores achieving the target
Total units sold
Management Recommendations
Based on the analysis, identify:

Best-performing store
Lowest-performing store
Most profitable category
Lowest-profit category
Store recommended for expansion
Category requiring additional marketing
Store-category combinations needing cost optimization
Store-category combinations requiring inventory reorder
Expected Final Output Format
SMARTMART RETAIL PERFORMANCE REPORT
===================================

COMPANY SUMMARY
---------------
Total Sales:
Total Cost:
Total Profit:
Overall Profit Margin:

BEST-PERFORMING STORE
---------------------
Store:
Sales:
Cost:
Profit:
Profit Margin:

MOST PROFITABLE CATEGORY
------------------------
Category:
Sales:
Cost:
Profit:
Profit Margin:

EXPANSION RECOMMENDATIONS
-------------------------
Eligible Stores:

COST OPTIMIZATION
-----------------
Store:
Category:
Cost:
Profit Margin:

INVENTORY REORDER
-----------------
Store:
Category:
Closing Stock:
Reorder Quantity:
Assignment Rules
Use NumPy for all calculations.
Do not manually calculate or hard-code answers.
Avoid Python loops wherever a NumPy vectorized solution is possible.
Use axis-based operations correctly.
Display store and category names along with calculated values.
Round percentage values to two decimal places.
Use Boolean indexing for filtering questions.
Use broadcasting for target, discount, and tax calculations.
Do not modify the original arrays unless specifically instructed.
Add comments explaining the purpose of important calculations.
Submission Requirements
Submit the assignment as a Jupyter Notebook containing:

Business scenario
Dataset creation
Question number and question description
NumPy solution below every question
Output for every solution
Final retail performance report
Minimum five business observations
Minimum three management recommendations'''


In [41]:
import numpy as np
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])
sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])
cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])
total_sales = np.sum(sales_data, axis=1)
total_cost = np.sum(cost_data, axis=1)
profit = total_sales - total_cost
overall_profit_margin = np.mean(profit / total_sales)
average_transaction_value = np.mean(total_sales)
highest_individual_sales_value = np.max(total_sales)
lowest_individual_sales_value = np.min(total_sales)
total_sales_by_store = np.sum(sales_data, axis=0)
total_cost_by_store = np.sum(cost_data, axis=0)
total_profit_by_store = total_sales_by_store - total_cost_by_store
profit_margin_by_store = total_profit_by_store / total_sales_by_store
number_of_category_targets_achieved = np.sum(sales_data >= 400000, axis=0)
total_units_sold_by_store = np.sum(sales_data, axis=1)
expansion_eligibility_by_store = total_units_sold_by_store >= 5
total_sales_by_category = np.sum(sales_data, axis=1)
total_cost_by_category = np.sum(cost_data, axis=1)
total_profit_by_category = total_sales_by_category - total_cost_by_category
profit_margin_by_category = total_profit_by_category / total_sales_by_category
average_sales_by_category = np.mean(sales_data, axis=0)
number_of_stores_achieving_target = np.sum(sales_data >= 400000, axis=1)
total_units_sold_by_category = np.sum(sales_data, axis=0)
best_performing_store_index = np.argmax(total_sales_by_store)
lowest_performing_store_index = np.argmin(total_sales_by_store)
most_profitable_category_index = np.argmax(total_profit_by_category)
lowest_profitable_category_index = np.argmin(total_profit_by_category)
store_recommended_for_expansion_index = np.argmax(expansion_eligibility_by_store)
category_requiring_additional_marketing_index = np.argmax(number_of_stores_achieving_target)
store_category_combinations_requiring_cost_optimization_indices = np.where(sales_data < 400000)
store_category_combinations_requiring_inventory_reorder_indices = np.where(sales_data < 300000)
print("Company Summary")
print("Total sales: ", total_sales)
print("Total cost: ", total_cost)
print("Total profit: ", profit)
print("Overall profit margin: ", overall_profit_margin)
print("Average transaction value: ", average_transaction_value)
print("Highest individual sales value: ", highest_individual_sales_value)
print("Lowest individual sales value: ", lowest_individual_sales_value)
print("Store Summary")
print("Total sales of Store: ", total_sales_by_store)
print("Total cost of Store: ", total_cost_by_store)
print("Total profit of Store: ", total_profit_by_store)
print("Profit margin of Store: ", profit_margin_by_store)
print("Number of category targets achieved: ", number_of_category_targets_achieved)
print("Total units sold by Store: ", total_units_sold_by_store)
print("Expansion eligibility of Store: ", expansion_eligibility_by_store)
print("Category saummary")
print("Total sales of Category: ", total_sales_by_category)
print("Total cost of Category: ", total_cost_by_category)
print("Total profit of Category: ", total_profit_by_category)
print("Profit margin of Category: ", profit_margin_by_category)
print("Average sales of Category: ", average_sales_by_category)
print("Number of stores achieving target: ", number_of_stores_achieving_target)
print("Total units sold by Category: ", total_units_sold_by_category)
print("Management Recommendations")
print("Best performing store: ", stores[best_performing_store_index])
print("Lowest performing store: ", stores[lowest_performing_store_index])
print("Most profitable category: ", categories[most_profitable_category_index])
print("Lowest profitable category: ", categories[lowest_profitable_category_index])
print("Store recommended for expansion: ", stores[store_recommended_for_expansion_index])
print("Category requiring additional marketing: ", categories[category_requiring_additional_marketing_index])
print("Store-category combinations requiring cost optimization: ", store_category_combinations_requiring_cost_optimization_indices)
print("Store-category combinations requiring inventory reorder: ", store_category_combinations_requiring_inventory_reorder_indices)
print("SMARTMART RETAIL PERFORMANCE REPORT")
print("==================================")
print("COMPANY SUMMARY")
print("---------------")
print("Total Sales          : ", total_sales)
print("Total Cost           : ", total_cost)
print("Total Profit         : ", profit)
print("Overall Profit Margin: ", overall_profit_margin)
print()
print("BEST-PERFORMING STORE")
print("--------------------")
print("Store        : ", stores[best_performing_store_index])
print("Sales        : ", total_sales_by_store[best_performing_store_index])
print("Cost         : ", total_cost_by_store[best_performing_store_index])
print("Profit       : ", total_profit_by_store[best_performing_store_index])
print("Profit Margin: ", profit_margin_by_store[best_performing_store_index])
print()
print("MOST PROFITABLE CATEGORY")
print("-----------------------")
print("Category     : ", categories[most_profitable_category_index])
print("Sales        : ", total_sales_by_category[most_profitable_category_index])
print("Cost         : ", total_cost_by_category[most_profitable_category_index])
print("Profit       : ", total_profit_by_category[most_profitable_category_index])
print("Profit Margin: ", profit_margin_by_category[most_profitable_category_index])
print("EXPANSION RECOMMENDATIONS")
print("------------------------")
print("Eligible Stores: ", stores[expansion_eligibility_by_store])
print()
print("COST OPTIMIZATION")
print("----------------")
print("Store        : ", stores[store_category_combinations_requiring_cost_optimization_indices[0]])
print("Category     : ", categories[store_category_combinations_requiring_cost_optimization_indices[1]])
print("Cost         : ", cost_data[store_category_combinations_requiring_cost_optimization_indices[0], store_category_combinations_requiring_cost_optimization_indices[1]])
print("Profit Margin: ", profit_margin_by_category[store_category_combinations_requiring_cost_optimization_indices[0]])
print()
print("INVENTORY REORDER")
print("----------------")
print("Store           : ", stores[store_category_combinations_requiring_inventory_reorder_indices[0]])
print("Category        : ", categories[store_category_combinations_requiring_inventory_reorder_indices[1]])
print("Closing Stock   : ", sales_data[store_category_combinations_requiring_inventory_reorder_indices[0], store_category_combinations_requiring_inventory_reorder_indices[1]])
print("Reorder Quantity: ", 100 - sales_data[store_category_combinations_requiring_inventory_reorder_indices[0], store_category_combinations_requiring_inventory_reorder_indices[1]])

Company Summary
Total sales:  [2270000 2295000 2310000 2820000 1980000]
Total cost:  [1665000 1685000 1710000 2065000 1475000]
Total profit:  [605000 610000 600000 755000 505000]
Overall profit margin:  0.26296725840097784
Average transaction value:  2335000.0
Highest individual sales value:  2820000
Lowest individual sales value:  1980000
Store Summary
Total sales of Store:  [4290000 2185000 1600000 1415000 1010000 1175000]
Total cost of Store:  [3250000 1660000 1145000 1045000  665000  835000]
Total profit of Store:  [1040000  525000  455000  370000  345000  340000]
Profit margin of Store:  [0.24242424 0.2402746  0.284375   0.2614841  0.34158416 0.2893617 ]
Number of category targets achieved:  [5 4 0 0 0 0]
Total units sold by Store:  [2270000 2295000 2310000 2820000 1980000]
Expansion eligibility of Store:  [ True  True  True  True  True]
Category saummary
Total sales of Category:  [2270000 2295000 2310000 2820000 1980000]
Total cost of Category:  [1665000 1685000 1710000 2065000 1